# -*- coding: utf-8 -*-
"""LançaDados_6faces_v1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cccD1aoQOBD1F1FH-YMkhnzvXFMX4UdS
"""

import random


S = []
print("Um dado de 6 faces será jogado 1000 vezes. Eis o resultado:")
print()
for i in range(0,1001):
  num = random.randint(1,6)
  S.append(num)
for i in range(1,7):
  print("O lado %i apareceu %i vezes."%(i,S.count(i)))

print()  
print("Lista dos valores obtidos a cada lançamento:", S)